const players=[{name:"Maya",handle:"@mayarose",color:"#d27b62",initials:"MR"},{name:"Theo",handle:"@theo.wav",color:"#629b83",initials:"TW"},{name:"Jules",handle:"@jules.mp3",color:"#8b7baf",initials:"JM"},{name:"Niko",handle:"@nikonight",color:"#d0a547",initials:"NN"}];
const tracks=[{title:"Electric Feel",artist:"MGMT",owner:"Maya"},{title:"Sweet Disposition",artist:"The Temper Trap",owner:"Theo"},{title:"Lisztomania",artist:"Phoenix",owner:"Jules"},{title:"Midnight City",artist:"M83",owner:"Niko"}];
const state={round:0,score:0,track:null,locked:false,timer:null};const $=id=>document.getElementById(id);
function show(id){["startScreen","roundScreen","resultScreen"].forEach(screen=>$(screen).classList.toggle("hidden",screen!==id));}
function toast(message){const node=$("toast");node.textContent=message;node.classList.add("show");setTimeout(()=>node.classList.remove("show"),2200)}
function renderGuesses(){
  $("guessGrid").innerHTML=players.map(player=>`<button class="guess-button" data-player="${player.name}"><span class="avatar" style="background:${player.color}">${player.initials}</span>${player.name}</button>`).join("");
  document.querySelectorAll(".guess-button").forEach(button=>button.addEventListener("click",()=>guess(button.dataset.player)));
}
function beginTimer(){let seconds=15;$("timer").textContent=seconds;clearInterval(state.timer);state.timer=setInterval(()=>{seconds-=1;$("timer").textContent=seconds;if(seconds<=0){clearInterval(state.timer);guess(null)}},1000)}
function startRound(){
  state.round+=1;state.track=tracks[(state.round-1)%tracks.length];state.locked=false;$("roundNumber").textContent=String(state.round).padStart(2,"0");$("trackTitle").textContent=state.track.title;$("trackArtist").textContent=`${state.track.artist} · someone’s rotation`;$('statusLabel').textContent="YOUR TURN TO GUESS";$("guessHint").textContent="Pick a player before time runs out";renderGuesses();beginTimer();
}
function guess(playerName){
  if(state.locked||!state.track)return;state.locked=true;clearInterval(state.timer);document.querySelectorAll(".guess-button").forEach(button=>{button.disabled=true;if(button.dataset.player===playerName)button.classList.add("selected")});const correct=playerName===state.track.owner;if(correct)state.score+=1;$("score").textContent=String(state.score).padStart(3,"0");$("guessHint").textContent=correct?"CORRECT · +1 POINT":playerName?`NOPE · IT WAS ${state.track.owner.toUpperCase()}`:"TIME · NO GUESS LOCKED";$("statusLabel").textContent=correct?"NICE CALL":"ROUND OVER";toast(correct?"Great ears +1":"The room knows now");setTimeout(()=>state.round<5?startRound():finishGame(),1300);
}
function startGame(){state.round=0;state.score=0;$("score").textContent="000";show("roundScreen");startRound()}
function finishGame(){clearInterval(state.timer);$("finalScore").textContent=String(state.score).padStart(3,"0");$("finalMessage").textContent=state.score>=4?"You are the room's resident music detective.":state.score>=2?"Not bad. Your friends are trickier than they look.":"The playlist remains mysterious.";show("resultScreen")}
$("startGame").addEventListener("click",startGame);$("playAgain").addEventListener("click",startGame);$("skipRound").addEventListener("click",()=>guess(null));$("howToPlay").addEventListener("click",()=>$("howPanel").classList.add("open"));$("closeHow").addEventListener("click",()=>$("howPanel").classList.remove("open"));$("copyRoom").addEventListener("click",async()=>{await navigator.clipboard?.writeText($("roomCode").textContent);toast("Room code copied")});$("leaveRoom").addEventListener("click",()=>{clearInterval(state.timer);show("startScreen");toast("Back to the start screen")});$("playButton").addEventListener("click",()=>toast(state.track?"Demo mode: imagine the first beat":"Start the room first"));

const Spotify={clientId:"",redirectUri:`${location.origin}${location.pathname}`,scopes:"user-read-private user-top-read",async authorize(){if(!this.clientId)return false;const verifier=crypto.randomUUID().replaceAll("-","");const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(verifier));const challenge=btoa(String.fromCharCode(...new Uint8Array(digest))).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");sessionStorage.setItem("spotify_verifier",verifier);location.href=`https://accounts.spotify.com/authorize?client_id=${this.clientId}&response_type=code&redirect_uri=${encodeURIComponent(this.redirectUri)}&code_challenge_method=S256&code_challenge=${challenge}&scope=${encodeURIComponent(this.scopes)}`;return true},async exchangeCode(code){const response=await fetch("https://accounts.spotify.com/api/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:this.clientId,grant_type:"authorization_code",code,redirect_uri:this.redirectUri,code_verifier:sessionStorage.getItem("spotify_verifier")})});if(!response.ok)throw Error("Spotify token exchange failed");return response.json()},async profile(token){const response=await fetch("https://api.spotify.com/v1/me",{headers:{Authorization:`Bearer ${token}`}});return response.json()},async topTracks(token){const response=await fetch("https://api.spotify.com/v1/me/top/tracks?limit=20&time_range=short_term",{headers:{Authorization:`Bearer ${token}`}});return response.json()}};
$("connectSpotify").addEventListener("click",async()=>{if(!(await Spotify.authorize()))toast("Add your Spotify client ID to enable connection")});
async function completeSpotifyConnection(){const code=new URLSearchParams(location.search).get("code");if(!code||!Spotify.clientId)return;try{const token=await Spotify.exchangeCode(code);const [profile,top]=await Promise.all([Spotify.profile(token.access_token),Spotify.topTracks(token.access_token)]);const name=profile.display_name||"Spotify friend";players[0]={name,handle:`@${profile.id}`,color:"#49ad76",initials:name.slice(0,2).toUpperCase()};if(top.items?.length)tracks[0]={title:top.items[0].name,artist:top.items[0].artists[0].name,owner:name};history.replaceState({},"",location.pathname);toast("Spotify connected")}catch(error){toast("Spotify connection could not be completed")}}
completeSpotifyConnection();
